export const parentingCategories = [
  { id: "all", name: "All" },
  { id: "feeding", name: "Feeding & Nutrition" },
  { id: "sleep", name: "Sleep & Rest" },
  { id: "development", name: "Development" },
  { id: "health", name: "Health & Safety" },
];

export const contentCategories = [
  { id: "blog", name: "Blogs" },
  { id: "video", name: "Videos" },
  { id: "podcast", name: "Podcasts" },
  { id: "article", name: "Articles" },
  { id: "toolkit", name: "Toolkits" },
];

// updated
export const resourcesData = {
  blogs: [
    {
      id: 1,
      title: "Newborn Care Basics",
      description: "Essential tips for taking care of your newborn in the first month.",
      author: "BabyCenter",
      type: "blog",
      category: "babycare",
      readTime: "5 min read",
      publishDate: "2024-04-12",
      tags: ["newborn", "care", "parenting"],
      url: "https://www.motherhoodindia.com/essential-newborn-care-tips-for-first-time-parents/",
    },
    {
      id: 2,
      title: "Nutrition During Pregnancy",
      description: "A guide to eating healthy for you and your baby.",
      author: "Mayo Clinic",
      type: "blog",
      category: "pregnancy",
      readTime: "7 min read",
      publishDate: "2024-03-20",
      tags: ["nutrition", "pregnancy", "health"],
      url: "https://www.hopkinsmedicine.org/health/wellness-and-prevention/nutrition-during-pregnancy",
    },
    {
      id: 3,
      title: "Managing Postpartum Recovery",
      description: "How to care for yourself physically and emotionally after birth.",
      author: "What To Expect",
      type: "blog",
      category: "postpartum",
      readTime: "6 min read",
      publishDate: "2024-01-15",
      tags: ["postpartum", "recovery", "self-care"],
      url: "https://www.whattoexpect.com/first-year/postpartum-recovery.aspx",
    },
    {
      id: 4,
      title: "Tips for Breastfeeding Success",
      description: "Lactation consultant advice for new moms.",
      author: "La Leche League",
      type: "blog",
      category: "breastfeeding",
      readTime: "5 min read",
      publishDate: "2024-05-05",
      tags: ["breastfeeding", "lactation", "feeding"],
      url: "https://www.thewomens.org.au/health-information/breastfeeding/breastfeeding-overview/tips-for-breastfeeding-success",
    },
    {
      id: 5,
      title: "Managing Parental Stress",
      description: "Effective strategies to cope with the mental load of parenting.",
      author: "Psychology Today",
      type: "blog",
      category: "mentalhealth",
      readTime: "6 min read",
      publishDate: "2024-02-10",
      tags: ["mental health", "stress", "parenting"],
      url: "https://www.unicef.org/parenting/mental-health/how-reduce-stress-parents",
    },
  ],

  videos: [
    {
      id: 6,
      title: "Newborn Bathing Tutorial",
      description: "Step-by-step guide to bathing your newborn safely.",
      author: "Johns Hopkins Medicine",
      type: "video",
      category: "babycare",
      readTime: "8 min video",
      publishDate: "2023-11-01",
      tags: ["bath", "baby", "hygiene"],
      url: "https://www.youtube.com/watch?v=P0eg44MJ-qg",
    },
    {
      id: 7,
      title: "Pregnancy Exercise Routine",
      description: "Safe workouts for expecting mothers.",
      author: "BodyFit by Amy",
      type: "video",
      category: "pregnancy",
      readTime: "30 min video",
      publishDate: "2023-10-15",
      tags: ["exercise", "pregnancy", "fitness"],
      url: "https://www.youtube.com/watch?v=lKx0sOz31C4&pp=ygUMI2RlbGl2ZXJ5Zml0",
    },
    {
      id: 8,
      title: "Postpartum Yoga Flow",
      description: "Gentle yoga routine for postpartum recovery.",
      author: "Yoga With Adriene",
      type: "video",
      category: "postpartum",
      readTime: "18 min video",
      publishDate: "2023-08-20",
      tags: ["yoga", "postpartum", "fitness"],
      url: "https://www.youtube.com/watch?v=EH18ikq09BQ&pp=ygUJI3VweW9nYXBw",
    },
    {
      id: 9,
      title: "Breastfeeding Positions Explained",
      description: "Visual guide to the best breastfeeding positions.",
      author: "Global Health Media Project",
      type: "video",
      category: "breastfeeding",
      readTime: "7 min video",
      publishDate: "2023-07-05",
      tags: ["breastfeeding", "positions", "feeding"],
      url: "https://www.youtube.com/watch?v=zBd5wVbwt9wc",
    },
    {
      id: 10,
      title: "Mindfulness for Parents",
      description: "Meditation techniques to help parents stay calm.",
      author: "Mindful.org",
      type: "video",
      category: "mentalhealth",
      readTime: "9 min video",
      publishDate: "2023-06-15",
      tags: ["mindfulness", "meditation", "mental health"],
      url: "https://www.youtube.com/watch?v=ZToicYcHIOU",
    },
  ],

  podcasts: [
    {
      id: 11,
      title: "The Longest Shortest Time",
      description: "Parenting stories for every stage.",
      author: "Hillary Frank",
      type: "podcast",
      category: "mentalhealth",
      readTime: "30 min episode",
      publishDate: "2024-04-01",
      tags: ["parenting", "stories", "mental health"],
      url: "https://longestshortesttime.com/",
    },
    {
      id: 12,
      title: "Pregnancy Confidential",
      description: "Week-by-week pregnancy advice.",
      author: "Parents Magazine",
      type: "podcast",
      category: "pregnancy",
      readTime: "20 min episode",
      publishDate: "2024-03-05",
      tags: ["pregnancy", "advice", "baby"],
      url: "https://open.spotify.com/show/3olBAebQEFKJmvbYHBdTr0",
    },
    {
      id: 13,
      title: "The Birth Hour",
      description: "Inspiring birth stories from around the world.",
      author: "Brynn Huntpalmer",
      type: "podcast",
      category: "pregnancy",
      readTime: "40 min episode",
      publishDate: "2024-02-15",
      tags: ["birth", "stories", "labor"],
      url: "https://thebirthhour.com/",
    },
    {
      id: 14,
      title: "Breastfeeding Talk",
      description: "Expert lactation advice and Q&A.",
      author: "Allison Tolman",
      type: "podcast",
      category: "breastfeeding",
      readTime: "25 min episode",
      publishDate: "2024-01-22",
      tags: ["breastfeeding", "advice", "lactation"],
      url: "https://www.breastfeedingtalkpodcast.com/",
    },
    {
      id: 15,
      title: "Parenting Beyond Discipline",
      description: "Positive parenting strategies.",
      author: "Erin Royer",
      type: "podcast",
      category: "mentalhealth",
      readTime: "35 min episode",
      publishDate: "2023-12-18",
      tags: ["discipline", "parenting", "family"],
      url: "https://open.spotify.com/show/67DtmiA0omcbC9Pen9PKpA",
    },
  ],

  articles: [
    
      {
    id: 16,
    title: "Introducing Solids: A Step-by-Step Guide",
    description: "Learn when and how to introduce solid foods to your baby, with tips for making the transition smooth",
    url: "https://www.betterhealth.vic.gov.au/health/healthyliving/eating-tips-for-babies",
    author: "Dr. Emily Parker",
    type: "feeding & Nutrition",
    readTime: "8 min read",
    publishDate: "2024-03-15",
    category: "feeding",
    tags: ["weaning", "nutrition", "first foods"]
  },
  {
    id: 17,
    title: "Establishing Healthy Sleep Habits",
    description: "Practical advice for helping your baby develop good sleep patterns from the start",
    url: "https://www.nationwidechildrens.org/family-resources-education/health-wellness-and-safety-resources/helping-hands/healthy-sleep-habits-for-infants-and-toddlers",
    author: "Sleep Consultant Team",
    type: "article",
    readTime: "10 min read",
    publishDate: "2024-02-28",
    category: "sleep",
    tags: ["sleep training", "routine", "newborn"]
  },
  {
    id: 18,
    title: "Baby-Proofing Your Home: The Complete Checklist",
    description: "Essential safety measures to protect your curious crawler and toddler",
    url: "https://www.thebump.com/a/checklist-babyproofing-part-1",
    author: "Safety First Organization",
    type: "article",
    readTime: "12 min read",
    publishDate: "2024-01-20",
    category: "health",
    tags: ["safety", "childproofing", "home"]
  },
  {
    id: 19,
    title: "Understanding Developmental Milestones",
    description: "What to expect in your baby's first year of growth and development",
    url: "https://www.cdc.gov/ncbddd/actearly/milestones/index.html",
    author: "Dr. Michael Chen",
    type: "article",
    readTime: "15 min read",
    publishDate: "2023-12-10",
    category: "development",
    tags: ["growth", "milestones", "first year"]
  },
  {
    id: 20,
    title: "The Importance of Tummy Time",
    description: "How tummy time helps your baby's development and ways to make it enjoyable",
    url: "https://safetosleep.nichd.nih.gov/reduce-risk/tummy-time",
    author: "Pediatric Physical Therapists",
    type: "article",
    readTime: "7 min read",
    publishDate: "2024-02-15",
    category: "development",
    tags: ["motor skills", "play", "development"]
  },
  {
      id: 21,
      title: "WHO Newborn Health Guidelines",
      description: "Official recommendations for newborn care.",
      author: "WHO",
      type: "article",
      category: "babycare",
      readTime: "10 min read",
      publishDate: "2024-01-01",
      tags: ["newborn", "guidelines", "health"],
      url: "https://www.who.int/publications/i/item/9789241504843",
    },
    {
      id: 22,
      title: "CDC Pregnancy and Vaccines",
      description: "Important vaccine recommendations for expecting mothers.",
      author: "CDC",
      type: "article",
      category: "pregnancy",
      readTime: "8 min read",
      publishDate: "2023-11-05",
      tags: ["vaccines", "pregnancy", "health"],
      url: "https://www.cdc.gov/vaccines/pregnancy/index.html",
    },
    {
      id: 23,
      title: "Postpartum Depression Facts",
      description: "Recognizing and managing postpartum depression.",
      author: "Mayo Clinic",
      type: "article",
      category: "postpartum",
      readTime: "6 min read",
      publishDate: "2023-09-15",
      tags: ["postpartum", "depression", "mental health"],
      url: "https://medlineplus.gov/ency/article/007215.htm#:~:text=Symptoms&text=Feelings%20of%20anxiety%2C%20irritation%2C%20tearfulness,Trouble%20sleeping",
    },
    {
      id: 24,
      title: "Breastfeeding Benefits",
      description: "Health benefits for both mother and baby.",
      author: "UNICEF",
      type: "article",
      category: "breastfeeding",
      readTime: "5 min read",
      publishDate: "2023-07-10",
      tags: ["breastfeeding", "benefits", "nutrition"],
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10631302/",
    },
    {
      id: 25,
      title: "Mindful Parenting Guide",
      description: "How to be a more present and calm parent.",
      author: "Greater Good Science Center",
      type: "article",
      category: "mentalhealth",
      readTime: "7 min read",
      publishDate: "2023-05-18",
      tags: ["mindfulness", "parenting", "calm"],
      url: "https://greatergood.berkeley.edu/topic/mindful_parenting/definition",
    },
  ],

  toolkits: [
    {
      id: 26,
      title: "UNICEF Early Childhood Toolkit",
      description: "Practical guidance for early childhood development.",
      author: "UNICEF",
      type: "toolkit",
      category: "other",
      readTime: "Comprehensive guide",
      publishDate: "2023-08-01",
      tags: ["toolkit", "development", "childcare"],
      url: "https://www.unicef.org/early-childhood-development",
    },
    {
      id: 27,
      title: "WHO Breastfeeding Toolkit",
      description: "Comprehensive breastfeeding best practices.",
      author: "WHO",
      type: "toolkit",
      category: "breastfeeding",
      readTime: "Comprehensive guide",
      publishDate: "2023-06-12",
      tags: ["breastfeeding", "guidelines", "toolkit"],
      url: "https://www.who.int/health-topics/breastfeeding",
    },
    {
      id: 28,
      title: "CDC Parenting Resources",
      description: "Guides to help parents manage child development stages.",
      author: "CDC",
      type: "toolkit",
      category: "other",
      readTime: "Comprehensive guide",
      publishDate: "2023-04-15",
      tags: ["parenting", "child development", "resources"],
      url: "https://www.cdc.gov/parents/index.html",
    },
    {
      id: 29,
      title: "Postpartum Care Plan",
      description: "Checklist and guide for mothers after childbirth.",
      author: "March of Dimes",
      type: "toolkit",
      category: "postpartum",
      readTime: "Comprehensive guide",
      publishDate: "2023-02-10",
      tags: ["postpartum", "care", "checklist"],
      url: "https://newmomhealth.com/healthcare/postpartum-toolkit-materials/",
    },
    {
      id: 30,
      title: "Pregnancy Planning Toolkit",
      description: "Step-by-step pregnancy preparation guide.",
      author: "Planned Parenthood",
      type: "toolkit",
      category: "pregnancy",
      readTime: "Comprehensive guide",
      publishDate: "2023-01-20",
      tags: ["pregnancy", "planning", "guide"],
      url: "https://www.plannedparenthood.org/learn/pregnancy",
    },
  ],
};